# Array properties
- Array can be of different dimension: 0D (scalar, single value), 1D (vector), 2D (matrix), 3D (matrix with multi layer)
- properties of array are:
    1. ndim
    2. shape (row * col) or (layer * row * col)
    3. size (no of element)
    4. dtype

In [6]:
# 0D array

import numpy as np

x = np.array(6)

print(f"x: {x}, \ndimension: {x.ndim}, \nshape: {x.shape}, \nsize: {x.size}, \ndata type: {x.dtype}")

x: 6, 
dimension: 0, 
shape: (), 
size: 1, 
data type: int64


In [7]:
# 1D or vector

x = np.array([1.3 , 2.2 , 1.7])

print(f"x: {x}, \ndimension: {x.ndim}, \nshape: {x.shape}, \nsize: {x.size}, \ndata type: {x.dtype}")

x: [1.3 2.2 1.7], 
dimension: 1, 
shape: (3,), 
size: 3, 
data type: float64


In [11]:
x =  np.array([[1, 2, 3], [4, 5, 6]])

print(f"x: {x}, \ndimension: {x.ndim}, \nshape: {x.shape}, \nsize: {x.size}, \ndata type: {x.dtype}")

x: [[1 2 3]
 [4 5 6]], 
dimension: 2, 
shape: (2, 3), 
size: 6, 
data type: int64


In [14]:
x = np.array([
    [
        [1, 2], [3, 4]
    ],
    [
        [5, 6], [7, 8]
    ],
    [
        [9, 10], [11, 12]
    ]
])

print(f"x: {x}, \ndimension: {x.ndim}, \nshape: {x.shape}, \nsize: {x.size}, \ndata type: {x.dtype}")

x: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], 
dimension: 3, 
shape: (3, 2, 2), 
size: 12, 
data type: int64
