In [11]:
import numpy as np

abc = np.array([1, 3, 5, 7])
print(abc)

zero = np.zeros(2)
print(zero)

one = np.ones(5)
print(one)

identity_matrix = np.eye(2)
print(identity_matrix)

[1 3 5 7]
[0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0.]
 [0. 1.]]
