In [2]:
import numpy as np

abc = np.array([1, 3, 5, 7]) # can be created from tuples also
print(abc)

zero = np.zeros(2)
print(zero)

one = np.ones(5)
print(one)


arr_range1 = np.arange(5)
print("arr_range1", arr_range1)

arr_range2 = np.arange(2, 10, 2)
print("arr_range2", arr_range2)

identity_matrix = np.eye(2)
print(identity_matrix)

[1 3 5 7]
[0. 0.]
[1. 1. 1. 1. 1.]
arr_range1 [0 1 2 3 4]
arr_range2 [2 4 6 8]
[[1. 0.]
 [0. 1.]]


In [ ]:
x = np.zeros(5)
y = np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
x = np.full(4, 3)
np.ones(5)*0.2

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [15]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x[:, 0:2]

array([[1, 2],
       [5, 6]])