# Indexing: Accessing a particular element from an array

In [14]:
# indexing in normal python list

x = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("first element ", x[0])
print("last element", x[-1])
print("specific element", x[0][2]) 

first element  [1, 2, 3]
last element [7, 8, 9]
specific element 3


In [15]:
# indexing in numpy array

import numpy as np
arr = np.array(x)

print(arr[0, 2]) # arr[row, col]

3


# Slicing: Taking a portion from an array

In [ ]:
# slicing in normal python list
x = [5, 10, 15, 20, 25, 30]

print("from index 1 to 3", x[1:4]) # [start:stop+1:step]
print("from index 1 to 3", x[1:4:2]) # [start:stop+1:step]
print("from index 0 to 3", x[:4])
print("from index 1 to end", x[1:])
print("reverse", x[::-1])
print(x[::2]) # every second element

from index 1 to 3 [10, 15, 20]
from index 1 to 3 [10, 20]
from index 0 to 3 [5, 10, 15, 20]
from index 1 to end [10, 15, 20, 25, 30]
reverse [30, 25, 20, 15, 10, 5]
[5, 15, 25]


In [20]:
# 1D slicing

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:3]) # arr[start:stop+1:step]
print(arr[1:3:2])
print(arr[:3])
print(arr[1:])
print(arr[::-1])


# 2D slicing
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2, 1:3]) # [row, col]

[2 3]
[2]
[1 2 3]
[2 3 4 5]
[5 4 3 2 1]
[[2 3]
 [5 6]]
