In [ ]:
import numpy as np

x = [1, 2, 3, 4, 5]

arr = np.array(x)

# print(f" sum: {arr.sum()} \n max: {arr.max()} \n min: {arr.min()} \n mean: {arr.mean()} \n variance: {arr.var()} \n std deviation: {arr.std()}")
print(f" sum: {np.sum(arr)} \n max: {np.max(arr)} \n min: {np.min(arr)} \n mean: {np.mean(arr)} \n variance: {np.var(arr)} \n std deviation: {np.std(arr)} \n index of min value: {np.argmin(arr)} \n index of max value: {np.argmax(arr)} \n cumulative sum: {np.cumsum(arr)} \n cumulative product: {np.cumprod(arr)} \n ")

 sum: 15 
 max: 5 
 min: 1 
 mean: 3.0 
 variance: 2.0 
 std deviation: 1.4142135623730951 
 index of min value: 0 
 index of max value: 4 
 cumulative sum: [ 1  3  6 10 15] 
 cumulative product: [  1   2   6  24 120] 
 


## Note:
- axis specifies the dimension that gets collapsed
- axis=0 collapse rows, axis=1 collapse columns


In [30]:
y = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]

arr = np.array(y)

print(f" array: {arr} \n sum: {np.sum(arr)} \n max: {np.max(arr)} \n min: {np.min(arr)} \n mean: {np.mean(arr)} \n variance: {np.var(arr)} \n std deviation: {np.std(arr)} \n index of min value: {np.argmin(arr)} \n index of max value: {np.argmax(arr)} \n ")

print(f" cumulative sum: {arr.cumsum()} \n cumulative sum axis 0: {arr.cumsum(axis=0)} \n cumulative sumaxis 1: {arr.cumsum(axis=1)} \n cumulative product: {np.cumprod(arr)} \n")


 array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
 sum: 55 
 max: 10 
 min: 1 
 mean: 5.5 
 variance: 8.25 
 std deviation: 2.8722813232690143 
 index of min value: 0 
 index of max value: 9 
 
 cumulative sum: [ 1  3  6 10 15 21 28 36 45 55] 
 cumulative sum axis 0: [[ 1  2  3  4  5]
 [ 7  9 11 13 15]] 
 cumulative sumaxis 1: [[ 1  3  6 10 15]
 [ 6 13 21 30 40]] 
 cumulative product: [      1       2       6      24     120     720    5040   40320  362880
 3628800] 

