# <b>Broadcasting:</b> if one array is smaller, stretch it to match the bigger one, so I can do math between them.
# <b>Rule:</b> Shapes must match, OR one of the array must be size 1 (which gets stretched/repeated).

In [11]:
# normal list vs numpy array addition

import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]

print("listt add result:", x+y)
print("array add result:", np.array(x) + np.array(y))

listt add result: [1, 2, 3, 4, 5, 6]
array add result: [5 7 9]


In [ ]:
# 1D + scalar

x = [1, 2, 3]

a = np.array(x)
b = 10 # [10, 10, 10]

print(a+b)

[11 12 13]


In [ ]:
# 2D + 1D

matrix1 = [
    [1, 2, 3],
    [4, 5, 6]
]
matrix2 = [10, 20, 30] #[[10, 20, 30], [10, 20, 30]]

result = np.array(matrix1) + np.array(matrix2)

print(result)


[[11 22 33]
 [14 25 36]]


In [12]:
x = [1, 2, 3]
y = [4, 5]
print(np.array(x) + np.array(y))

ValueError: operands could not be broadcast together with shapes (3,) (2,) 